### ISSUE TITLE
JC TRex Newer versions

### ISSUE THREAD

**Issue by jredfox** [jredfox/silkspawners_rewrite#28]
Version:1.8.1
Issue:trex has open gl errors when rendering in inventory. Will have to debug and see if I can figure out if it is on my end the dev thinks it is on my end

**Comment by SethWilliamson** [comment]
This smells possibly related. With the latest update, I am failing to even load to the main menu with a NullPointerException.

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from silkspawners (silkspawners)
Caused by: java.lang.NullPointerException
```

![Crash Screen](https://i.imgur.com/FtH1Ws6.png)

## Versions
Forge 14.23.5.2811
EvilNotchLib 1.2.3-Pre-Release2 (did you mean to flag this as a full release instead of alpha/beta?)
Silk Spawners 1.8.1

## Logs
[Crash Report](https://paste.dimdev.org/xijivucecu.sql)
[Full latest.log from crash](https://paste.dimdev.org/sefizayuxa.md)

## Things I've tried
* Rolling back to EvilNotchLib-SNAPSHOT-80 and SilkSpawners-1.8.06 and the problem goes away.
* Test environment with just the three mods listed above works fine, as I'm sure it does for you. There is some mod interaction I haven't pinned down. 

## Things I'll continue trying
It'll take a while, but I'll see if I can narrow it down to a specific mod. After creating a clean test environment, I've started adding back in the other mods, starting with the most likely offenders (foamfix, betterfps, itemzoom, justenoughids, resourceloader....) No crashes yet. I'll let you know if I pin it down. I figured I'd post the logs here in case something jumps at you about the logs and the recent development you've done.

**Comment by jredfox** [comment]
this is a separate issue why would you comment on a separate issue while posting your main issue

**Comment by SethWilliamson** [comment]
Will do. I saw the rendering and erred on the side of not doing a double post. 
Good news is I narrowed down the mod interaction. Will post seperately in a moment.

**Comment by jredfox** [comment]
I think I figured it out try this jar:
https://www.mediafire.com/file/ac9rjyj23k8c1mm/EvilNotchLib-Dev.jar/file

Also rendering has nothing to do with your crash

**Comment by jredfox** [comment]
@SethWilliamson join my discord let me send you this and a private silkspawners build

**Comment by jredfox** [comment]
It is either caused by a needed reset opengl method or it's on their side doesn't appear to be on my side at all if I don't need a reset code

**Comment by jredfox** [comment]
try TEISR if it works disable asm class by class till I find the culprit. if it doesn't update the dev that the vanilla mod didn't work on rendering the entity.

**Comment by jredfox** [comment]
the issue is on their side. Unless they directly prove otherwise I simply am calling render with full open gl reset codes in place
